# PostgreSQL

default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: clinical_safety_development
  host: localhost
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 5000

test:
  <<: *default
  database: clinical_safety_test

production:
  <<: *default
  database: myapp_test

