# PostgreSQL


default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: clinical_safety_development
  host: <%= ENV['DATABASE_URL'] %>
  port: 5432
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 5000

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: myapp_test
#   pool: 5
#   username: brenden
#   password:
#   timeout: 5000
  
# production:
#   adapter: postgresql
#   encoding: unicode
#   database: myapp_test
#   pool: 5
#   username: brenden
#   password:
#   timeout: 5000
